name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run: |
            echo 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 | docker login ghcr.io -u amirioelmos --password-stdin
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/behinkar/front:latest
      - name: Docker Push
        run: docker push ghcr.io/behinkar/front:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/frontend
            docker compose pull web
            docker compose up -d
          host: ${{ secrets.HOST }}
          user: root
          port: 2233
          pass: ${{ secrets.PASSWORD }}
