name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag amiriodocker/noron:behinkar-fornt-latest
      - name: Docker Push
        run: docker push amiriodocker/noron:behinkar-fornt-latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/frontend
            docker compose pull web
            docker compose up -d
          host: ${{ secrets.HOST }}
          user: root
          port: 2233
          pass: ${{ secrets.PASSWORD }}
