name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: docker login
      #   run: |
      #     echo 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 | docker login ghcr.io -u amirioelmos --password-stdin
      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          registry: ghcr.io
          username: $GITHUB_USER
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        env:
          REGISTRY: ghcr.io
          OWNER: behinkar
          IMAGE_NAME: ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: final
          push: true
          tags: |
            $REGISTRY/$OWNER/$IMAGE_NAME:$(date +%s)
          build-args: |
            ENVIRONMENT=production
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/frontend
            docker compose pull web
            docker compose up -d
          host: ${{ secrets.HOST }}
          user: root
          port: 2233
          pass: ${{ secrets.PASSWORD }}
